@EventIngestion.Api_HostAddress = http://localhost:5001

POST {{EventIngestion.Api_HostAddress}}/events
Content-Type: application/json
Idempotency-Key: idem-1001
X-Correlation-Id: 11111111-1111-1111-1111-111111111111

{
	"event_type": "user.created",
	"occurred_at": "2026-02-23T03:00:00Z",
	"source": "postman",
	"tenant_id": "tenant-acme",
	"idempotency_key": "body-key-ignored-when-header-present",
	"payload": {
		"user_id": "u-1001",
		"email": "user@example.com"
	}
}

###

POST {{EventIngestion.Api_HostAddress}}/events
Content-Type: application/json
Idempotency-Key: idem-1001

{
	"event_type": "user.created",
	"source": "postman",
	"tenant_id": "tenant-acme",
	"payload": {
		"user_id": "u-1001",
		"email": "user@example.com"
	}
}
